# Site settings
title: slee2
description: 'Business Card Page'
url: 'https://lee-seungju.github.io/'
baseurl: ''
profilepic: '/images/slee2.jpg'
bkimage: '/images/back1.png'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Thomas Zühlke'
  email: info@thomas-zuehlke.de
  twitter_username: thomzuehlke
  facebook_username: 이승주
  github_username:  Lee-seungju
  # linkedin_username:  thomas-zühlke-889182165
  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
