# Site settings
title: slee2
description: 'Business Card Page'
url: 'https://impartial-goldfish-c9b.notion.site/4b0ab92f85ec49cd8f35ee0dec9dc9f0'
baseurl: ''
profilepic: '/images/slee2.jpg'
bkimage: '/images/back1.png'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Thomas Zühlke'
  email: info@thomas-zuehlke.de
  # twitter_username: thomzuehlke
  facebook_username: 100002673633503
  github_username:  Lee-seungju
  linkedin_username:  5671
  # meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
